name: Lint, format and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build image
        run: make build

      - name: Lint, format check and test (Docker)
        run: make check-all
